name: Build spine-godot GDExtension (Godot 4.x)

on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string
        default: "Godot tag not specified!"
      godot_version:
        required: true
        type: string
        default: "Godot version not specified!"
      godot_cpp_api_version:
        required: true
        type: string
        default: "Godot C++ API version not specified!"
      dev:
        required: true
        type: boolean
        default: false

env:
  GODOT_TAG: ${{ inputs.godot_tag }}
  GODOT_VERSION: ${{ inputs.godot_version }}
  GODOT_CPP_API_VERSION: ${{ inputs.godot_cpp_api_version }}
  DEV_BUILD: ${{ inputs.dev }}

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps-4

      - name: Build GDExtension
        shell: bash
        run: |
          cd spine-godot/build
          ./setup-extension.sh $GODOT_TAG $DEV_BUILD
          ./build-extension.sh windows

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gdextension-windows-${{ env.GODOT_TAG }}
          path: spine-godot/example-v4-extension/bin/windows/*.dll
          retention-days: 1

  build-linux-x86_64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps-4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev

      - name: Build GDExtension
        run: |
          cd spine-godot/build
          ./setup-extension.sh $GODOT_TAG $DEV_BUILD
          ./build-extension.sh linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gdextension-linux-x86_64-${{ env.GODOT_TAG }}
          path: spine-godot/example-v4-extension/bin/linux/*.so
          retention-days: 1

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python and scons
        uses: ./.github/actions/setup-godot-deps-4

      - name: Build GDExtension
        run: |
          cd spine-godot/build
          ./setup-extension.sh $GODOT_TAG $DEV_BUILD
          ./build-extension.sh macos

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gdextension-macos-${{ env.GODOT_TAG }}
          path: spine-godot/example-v4-extension/bin/macos/**/*
          retention-days: 1
